config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :classrooms do
    member do
      patch :update_current_seating_chart
    end
  end
  resources :seating_charts
  resources :students
  
  # Defines the root path route ("/")
  root "classrooms#index"
end

app/models/seating_chart.rb
# == Schema Information
#
# Table name: seating_charts
#
#  id           :bigint           not null, primary key
#  columns      :integer
#  rows         :integer
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  classroom_id :bigint           not null
#
# Indexes
#
#  index_seating_charts_on_classroom_id  (classroom_id)
#
# Foreign Keys
#
#  fk_rails_...  (classroom_id => classrooms.id)
#
class SeatingChart < ApplicationRecord
  belongs_to :classroom
  has_many :desks, dependent: :destroy

  # TODO: validate that the seating chart is not larger than the classroom to which it belongs.
  validates :rows, :columns, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :title, presence: true

  validate :check_rows_and_columns

  private

  def check_rows_and_columns
    check_rows && check_columns
  end

  def check_rows
    if rows > classroom.rows
      errors.add(:base, "Seating chart cannot have more rows than classroom.")
      return false
    end

    true
  end

  def check_columns
    if columns > classroom.columns
      errors.add(:base, "Seating chart cannot have more columns than classroom.")
      return false
    end

    true
  end
end

app/controllers/seating_charts_controller.rb
class SeatingChartsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_seating_chart, only: [:edit, :update, :destroy]

  def new
    @seating_chart = SeatingChart.new
  end

  def create
    @seating_chart = SeatingChart.new(seating_chart_params)

    if @seating_chart.save
      # TODO: What happens here? display the new seating chart?
    else
      # TODO: Display errors using Turbo frames.
      render :new
    end
  end

  def edit
  end

  def update
    if @seating_chart.update(seating_chart_params)
      # TODO: What happens here? Disaply the edited seating chart?
    else
      # TODO: Dispaly error using Turbo frames
      render :edit
    end
  end

  def destroy
    if @seating_chart.destroy
      # TODO: flash message destroy successful
    else
      # TODO: flash message destroy failed
    end
  end

  private

  def set_seating_chart
    @seating_chart = SeatingChart.find(params[:id])
  end

  def seating_chart_params
    params.require(:seating_chart).permit(:title, :rows, :columns, :classroom_id)
  end
end

app/helpers/seating_charts_helper.rb
module SeatingChartsHelper
end

app/views/seating_charts/_seating_chart.html.erb
<div class="grid grid-cols-5 gap-4">
  <% @classroom.current_seating_chart.desks.includes([:student]).each do |desk| %>
    <div class="border p-4 flex justify-center items-center">
      <div style="grid-template-rows: repeat(<%= @classroom.current_seating_chart.rows %>, minmax(0, 1fr));" class="grid gap-4">
        <%= desk.student ? desk.student.first_name : desk.row_position + desk.column_position %>
      </div>
    </div>
  <% end %>
</div>

app/views/seating_charts/_select_seating_chart.html.erb
<div data-controller="select-seating-chart">
  <%= form_with url: update_current_seating_chart_classroom_path(@classroom), method: :patch, data: { turbo_frame: "displayed_seating_chart", "select-seating-chart-target": "form" } do %>
    <label for="select-seating-charts" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Change seating chart</label>
    <%= select_tag :current_seating_chart_id, options_from_collection_for_select(@seating_charts, :id, :title, @seating_chart.id), class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", data: { action: "change->select-seating-chart#submitForm" } %>
  <% end %>
</div>